variable "source_bucket" {}
variable "account_code" {}
variable "env" {}
variable "version_lambda" {}
variable "region_code" {}
variable "name" {}
variable "notification_filter_prefix" {}
variable "notification_filter_suffix" {}
variable "sftp_target_hostname" {}
variable "sftp_target_user_ssm" {}
variable "sftp_target_pass_ssm" {}
variable "sftp_target_port" {}
variable "sftp_target_directory" {}
variable "feedname" {}
