variable "source_bucket" {}
variable "account_code" {}
variable "env" {}
variable "region_code" {}
variable "name" {}
variable "glue_job_name" {}
variable "bucket_config" {}
variable "copybook_prefix" {}
variable "header_copybook_prefix" {}
variable "prep2exchange_function_name" {}
variable "target_bucket" {}
variable "sf_function_name" {}
